# Site Settings
title: "vertis.io"
email: "me@vertis.io"
description: "Writings about development, future technology and life"
baseurl: ""
url: "https://vertis.io"
logourl: "/assets/img/bloglogo.jpg"
fa-logo: "fa-bookmark-o"
plugins: [jekyll-paginate]
paginate: 5

# Author Settings
author_name: "Luke Chadwick"
author_url: "https://vertis.io"
author_bio: "Geek since birth. Futurist. Lover. Idealist."
author_email: "me@vertis.io"
author_image: "/assets/img/authorimage.jpg"

# Social Settings
twitter_url: "https://twitter.com/vertis"
facebook_url: "https://facebook.com"
github_url: "https://github.com/vertis"
youtube_url: "https://youtube.com"
dribbble_url: "https://dribbble.com"
googleplus_url: "https://google.com/plus"
instagram_url: "https://instagram.com"
pinterest_url: "https://pinterest.com"
linkedin_url: "https://linkedin.com"
feed_url: "https://feeds.feedburner.com/vertis"

# Theme Settings
theme_disqus_shortname: "ecko"
theme_google_comments: false
theme_analytics_id: "UA-1940507-6"
theme_analytics_domain: "vertis.io"
theme_reading_time: true
theme_autoload_comments: false
theme_always_show_nav: false

# SASS Settings
# DO NOT MODIFY
sass:
  sass_dir: "assets/css/"
  style: :compressed

# Build Settings
markdown: kramdown
permalink: pretty
paginate_path: "/blog/page:num/"

exclude:
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - yarn.lock
  - CNAME

header_nav_links:
  - href: /blog
    name: Blog
  - href: /consulting
    name: Consulting
  - href: /about
    name: About Me
  - href: /contact
    name: Contact
