---
layout: post
title: "Rails is not a ghetto, it's a train station."
---

Before I launch into my response to <a title="Rails is still a Ghetto" href="http://www.rubyrailways.com/rails-is-still-a-ghetto/">Peter Szinek</a>, you need to know some background. <a title="@merbist" href="http://twitter.com/merbist">Matt Aimonetti</a> made a <a href="http://www.slideshare.net/mattetti/couchdb-perform-like-a-pr0n-star">presentation</a> at <a href="http://gogaruco.com/">GoGaRuCa</a> on CouchDB, which included sexual references and supposedly explicit images. I've looked over the presentation (which may or may not have the same content as the one at the event) and I have to say that I found it to be pretty tame considering the hype that had spread before it. When I first read the story (found <a href="http://www.ultrasaurus.com/sarahblog/2009/04/gender-and-sex-at-gogaruco/">here</a> and <a href="http://dyepot-teapot.com/2009/04/25/dear-fellow-rubyists/">here</a>) it was framed in 'how to scare women away from your development community'. <a href="http://www.twitter.com/dhh">DHH</a> and probably many others<a href="http://www.renaebair.com/2009/04/27/perform-like-a-frag-star/"></a>, <a href="http://http://www.loudthinking.com/posts/39-im-an-r-rated-individual">responded</a> <a href="http://www.loudthinking.com/posts/40-alpha-male-programmers-arent-keeping-women-out">strongly</a> to the controversy. I'm particularly fond of Renae Bair's <a href="http://www.renaebair.com/2009/04/27/perform-like-a-frag-star/">post</a>.<a href="http://www.renaebair.com/2009/04/27/perform-like-a-frag-star/">
</a>

This morning when I got to work I was greeted by another story...about how rails is still a ghetto.  I have to disagree with the argument. Yes if you go to India and go to a Hindu temple you should take off your shoes, and you should be refined enough to KNOW to take off your shoes, either that or the shoes at the door should give you the heads up. This line of reasoning isn't relevant for a rails conference, because there is no guideline anywhere that says, 'should not show pictures of that nature'. It may well have been a bad decision, but there without precedent, how was he to know.

This is where the argument that professionalism comes in. I certainly wouldn't dare using a presentation like that at my work, because they're card holding accountants and lawyers. The development community (in particular web 2.0) has a reputation for riding on the edge, this is not just rails (which has been pointed out by others), but many other frameworks/languages that consider themselves groundbreaking. Clearly there is a disconnect here, between being passionate and fun, and relaxing from corporate strictures. Professionalism should have had everybody there wearing a suit and tie, but I would bet they weren't.

There has been plenty of coverage about this less than newsworthy event, so I'll not waste any more time on it. Another couple of days, and it will have disappeared from reddit, digg, etc &amp; and will be forgotten. The majority of people that use Rails don't care about posturing and hype that people are putting so much effort into...that's just a way of big noting blogs and looking important. Rails isn't a ghetto, if anything it's a train station, with a lot of people getting on and going places and a few people that feel the need to hang around and cause trouble. I'm not saying you don't have a right to dislike his presentation, but don't include the rest of us. Don't pretend like he did something wrong just because you don't like it. If you don't like the way he did the presentation put together a better presentation and you be the one standing on stage.

On that note I'm going back to work.
